-- 删除数据库
DROP TABLE IF EXISTS txn0;
-- 创建数据库
CREATE TABLE IF NOT EXISTS txn0  (k INT UNIQUE NOT NULL PRIMARY KEY, v INT NOT NULL);
SET GLOBAL tidb_txn_mode = 'optimistic';
-- 
INSERT INTO txn0 (k, v) VALUES (10, 1) ON DUPLICATE KEY UPDATE v = 1;
BEGIN;
INSERT INTO txn0 (k, v) VALUES (7, 3) ON DUPLICATE KEY UPDATE v = 3;
INSERT INTO txn0 (k, v) VALUES (10, 2) ON DUPLICATE KEY UPDATE v = 2;
SELECT v FROM txn0 WHERE k = 10;
COMMIT;